name: test

on: [push]

jobs:
  test:

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    
    steps:
    - uses: actions/checkout@v1
    - name: make test
      if: runner.os != 'Windows'
      run: make test
    - name: cmake test
      if: runner.os == 'Windows'
      run: |
        cmake -G 'Visual Studio 16 2019' -A x64 -DCMAKE_BUILD_TYPE=Release -DBUILD_TESTING=ON
        cmake --build .
        ctest --output-on-failure
